
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A B SALTO_LINEA\nlineas : lineas linea\n| linea\nlinea : cadena SALTO_LINEAlinea : error SALTO_LINEA\ncadena : A B B\n| A cadena B\n'
    
_lr_action_items = {'error':([0,1,2,6,7,8,],[4,4,-2,-1,-3,-4,]),'A':([0,1,2,5,6,7,8,],[5,5,-2,5,-1,-3,-4,]),'$end':([1,2,6,7,8,],[0,-2,-1,-3,-4,]),'SALTO_LINEA':([3,4,11,12,],[7,8,-5,-6,]),'B':([5,9,10,11,12,],[9,11,12,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lineas':([0,],[1,]),'linea':([0,1,],[2,6,]),'cadena':([0,1,5,],[3,3,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lineas","S'",1,None,None,None),
  ('lineas -> lineas linea','lineas',2,'p_lineas','G3.py',17),
  ('lineas -> linea','lineas',1,'p_lineas','G3.py',18),
  ('linea -> cadena SALTO_LINEA','linea',2,'p_linea_acepta','G3.py',23),
  ('linea -> error SALTO_LINEA','linea',2,'p_linea_no_acepta','G3.py',27),
  ('cadena -> A B B','cadena',3,'p_cadena','G3.py',33),
  ('cadena -> A cadena B','cadena',3,'p_cadena','G3.py',34),
]
