
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AB ABB SALTO_LINEA\nlineas : lineas linea\n| linea\n\nlinea : AB SALTO_LINEA\n| ABB SALTO_LINEA\nlinea : error SALTO_LINEA'
    
_lr_action_items = {'AB':([0,1,2,6,7,8,9,],[3,3,-2,-1,-3,-4,-5,]),'ABB':([0,1,2,6,7,8,9,],[4,4,-2,-1,-3,-4,-5,]),'error':([0,1,2,6,7,8,9,],[5,5,-2,-1,-3,-4,-5,]),'$end':([1,2,6,7,8,9,],[0,-2,-1,-3,-4,-5,]),'SALTO_LINEA':([3,4,5,],[7,8,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lineas':([0,],[1,]),'linea':([0,1,],[2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lineas","S'",1,None,None,None),
  ('lineas -> lineas linea','lineas',2,'p_lineas','G4.py',17),
  ('lineas -> linea','lineas',1,'p_lineas','G4.py',18),
  ('linea -> AB SALTO_LINEA','linea',2,'p_linea_acepta','G4.py',24),
  ('linea -> ABB SALTO_LINEA','linea',2,'p_linea_acepta','G4.py',25),
  ('linea -> error SALTO_LINEA','linea',2,'p_linea_no_acepta','G4.py',30),
]
