
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A B SALTO_LINEA\nlineas : lineas linea\n| linea\nlinea : A sub_cadena B SALTO_LINEAlinea : error SALTO_LINEA\nsub_cadena :\n| A B sub_cadena\n'
    
_lr_action_items = {'A':([0,1,2,3,5,8,9,12,],[3,3,-2,6,-1,-4,6,-3,]),'error':([0,1,2,5,8,12,],[4,4,-2,-1,-4,-3,]),'$end':([1,2,5,8,12,],[0,-2,-1,-4,-3,]),'B':([3,6,7,9,11,],[-5,9,10,-5,-6,]),'SALTO_LINEA':([4,10,],[8,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lineas':([0,],[1,]),'linea':([0,1,],[2,5,]),'sub_cadena':([3,9,],[7,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lineas","S'",1,None,None,None),
  ('lineas -> lineas linea','lineas',2,'p_lineas','G5.py',17),
  ('lineas -> linea','lineas',1,'p_lineas','G5.py',18),
  ('linea -> A sub_cadena B SALTO_LINEA','linea',4,'p_linea_acepta','G5.py',23),
  ('linea -> error SALTO_LINEA','linea',2,'p_linea_no_acepta','G5.py',27),
  ('sub_cadena -> <empty>','sub_cadena',0,'p_sub_cadena','G5.py',33),
  ('sub_cadena -> A B sub_cadena','sub_cadena',3,'p_sub_cadena','G5.py',34),
]
