
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CERO SALTO_LINEA UNO\nlineas : lineas linea\n| linea\nlinea : capicua SALTO_LINEAlinea : error SALTO_LINEA\ncapicua :\n| CERO\n| UNO\n| CERO capicua CERO\n| UNO capicua UNO\n'
    
_lr_action_items = {'error':([0,1,2,7,8,9,],[4,4,-2,-1,-3,-4,]),'SALTO_LINEA':([0,1,2,3,4,5,6,7,8,9,12,13,],[-5,-5,-2,8,9,-6,-7,-1,-3,-4,-8,-9,]),'CERO':([0,1,2,5,6,7,8,9,10,12,13,],[5,5,-2,5,5,-1,-3,-4,12,-8,-9,]),'UNO':([0,1,2,5,6,7,8,9,11,12,13,],[6,6,-2,6,6,-1,-3,-4,13,-8,-9,]),'$end':([1,2,7,8,9,],[0,-2,-1,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lineas':([0,],[1,]),'linea':([0,1,],[2,7,]),'capicua':([0,1,5,6,],[3,3,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lineas","S'",1,None,None,None),
  ('lineas -> lineas linea','lineas',2,'p_lineas','G1.py',27),
  ('lineas -> linea','lineas',1,'p_lineas','G1.py',28),
  ('linea -> capicua SALTO_LINEA','linea',2,'p_linea_capicua','G1.py',33),
  ('linea -> error SALTO_LINEA','linea',2,'p_linea_no_capicua','G1.py',37),
  ('capicua -> <empty>','capicua',0,'p_capicua','G1.py',43),
  ('capicua -> CERO','capicua',1,'p_capicua','G1.py',44),
  ('capicua -> UNO','capicua',1,'p_capicua','G1.py',45),
  ('capicua -> CERO capicua CERO','capicua',3,'p_capicua','G1.py',46),
  ('capicua -> UNO capicua UNO','capicua',3,'p_capicua','G1.py',47),
]
